version: '3.9'
services:
  frontend:
    build: ./frontend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    # volumes:
    #   - ./frontend/machinelearningidefrontend:/code
      # - ${PWD}/frontend
      # - /app/node_modules
    
  backend:
    build: ./backend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 8080:8080
    # volumes:
    #   - backendvol:/code

# volumes:
#   frontendvol:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: 'frontend/machinelearningidefrontend'
#   backendvol: